= Spring Boot Microservices + AccuREST

This project contains a *very simple* demo of using http://martinfowler.com/articles/consumerDrivenContracts.html[consumer-driven contracts] to verify the interactions between microservices.
It leverages http://projects.spring.io/spring-boot[Spring Boot] for both the provider and consumer services.

Testing is achieved using the http://codearte.github.io/accurest[AccuREST] project.

== Running the Demo

. Run the tests using Maven:
+
----
$ cd microservices-accurest-provider
$ ./mvnw clean test
----

. This will result in the creation of a http://wiremock.org/[WireMock] mapping file and a test code to verify this API server actually provides the expected contract. Here's a current example:
+
`target/accurest/mappings/requestForFoos.json`
+
[source,json]
----
{
  "uuid" : "b66bd99c-0319-4e09-81cc-415f7249542e",
  "request" : {
    "url" : "/foos",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "body" : "[{\"value\":42},{\"value\":100}]",
    "headers" : {
      "Content-Type" : "application/json;charset=UTF-8"
    }
  }
}
----
+
`target/generated-test-sources/io/pivotal/microservices/accurest/provider/AccurestTest.java`
+
[source,java]
----
package io.pivotal.microservices.accurest.provider;

import com.jayway.jsonpath.DocumentContext;
import com.jayway.jsonpath.JsonPath;
import com.jayway.restassured.module.mockmvc.specification.MockMvcRequestSpecification;
import com.jayway.restassured.response.ResponseOptions;
import io.pivotal.microservices.accurest.provider.MvcTest;
import org.junit.Test;

import static com.jayway.restassured.module.mockmvc.RestAssuredMockMvc.*;
import static com.toomuchcoding.jsonassert.JsonAssertion.assertThatJson;
import static org.assertj.core.api.Assertions.assertThat;

public class AccurestTest extends MvcTest {

	@Test
	public void validate_requestForFoos() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();

		// when:
			ResponseOptions response = given().spec(request)
					.get("/foos");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).isEqualTo("application/json;charset=UTF-8");
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).array().contains("value").isEqualTo(100);
			assertThatJson(parsedJson).array().contains("value").isEqualTo(42);
	}

}
----
+
Mappings files can be generated by `./mvnw clean accurest:convert` and test code can be generated by `./mvnw clean accurest:generateTests`
+
Standalone stub server can run with this mappings files and WireMock
+
----
$ ./mvnw clean accurest:convert accurest:run
----
+
You can access this stub server as follows:
+
----
$ curl localhost:8080/foos
[{"value":42},{"value":100}]
----
+
Press `Enter` to stop this server.


. Next, we want to make the jar file which includes mapping json file to embed this stub in consumer app:
+
----
$ ./mvnw clean install
----
+
This creates `target/microservices-accurest-provider-0.0.1-SNAPSHOT-stubs.jar` and copies this to `io.pivotal.microservices.accurest.provider:microservices-accurest-provider:0.0.1-SNAPSHOT:stubs` in your local maven repository.
+
Stub jar file can also be created by `./mvnw clean accurest:convert accurest:generateStubs`.
Of course, you can share this stub jar across PCs by `./mvnw deploy`.

. Next, we can test the consumer side without running the producer by using WireMock :
+
----
$ cd ../microservices-accurest-consumer
$ ./mvnw clean test
----

